
import { Question } from './types';

export const QUESTIONS: Question[] = [
  // Part 1
  { id: 1, text: "Which characteristic refers to the computer's ability to process millions of instructions per second?", options: ["Accuracy", "Speed", "Diligence", "Versatility"], correctAnswer: 1, category: "Characteristics" },
  { id: 2, text: "A computer does not suffer from tiredness or lack of concentration. This is called:", options: ["Versatility", "Storage Capability", "Diligence", "Accuracy"], correctAnswer: 2, category: "Characteristics" },
  { id: 3, text: "\"Versatility\" in computers means:", options: ["It can store large amounts of data.", "It provides a high degree of accuracy.", "It can perform different types of tasks with the same ease.", "It works at a very high speed."], correctAnswer: 2, category: "Characteristics" },
  { id: 4, text: "Which of the following is a significant limitation of a computer?", options: ["Lack of speed", "Small storage", "Cannot take its own decisions", "High cost"], correctAnswer: 2, category: "Limitations" },
  { id: 5, text: "Computer can only perform tasks that it has been:", options: ["Forced to do", "Programmed to do", "Asked by the neighbor", "Bought for"], correctAnswer: 1, category: "Limitations" },
  // Part 2
  { id: 6, text: "First-generation computers (1940-1956) used ________ for circuitry:", options: ["Transistors", "Vacuum tubes", "Integrated Circuits", "Microprocessors"], correctAnswer: 1, category: "Generations" },
  { id: 7, text: "Second-generation computers (1956-1963) replaced vacuum tubes with:", options: ["Magnetic Tapes", "Transistors", "Silicon Chips", "AI"], correctAnswer: 1, category: "Generations" },
  { id: 8, text: "Third-generation computers (1964-1971) used ________ for circuitry:", options: ["Transistors", "Integrated Circuits (ICs)", "VLSI", "Vacuum tubes"], correctAnswer: 1, category: "Generations" },
  { id: 9, text: "Fourth-generation computers (1971-Present) are characterized by the use of:", options: ["VLSIC (Microprocessors)", "Magnetic Drums", "Transistors", "Tubes"], correctAnswer: 0, category: "Generations" },
  { id: 10, text: "Fifth-generation computing is based on:", options: ["Transistors", "Artificial Intelligence (AI)", "Vacuum tubes", "ICs"], correctAnswer: 1, category: "Generations" },
  { id: 11, text: "Which generation saw the development of the Internet?", options: ["Second", "Third", "Fourth", "Fifth"], correctAnswer: 2, category: "Generations" },
  { id: 12, text: "Assembly language and High-level languages (COBOL/FORTRAN) were first used in:", options: ["1st Gen", "2nd Gen", "3rd Gen", "4th Gen"], correctAnswer: 1, category: "Generations" },
  // Part 3
  { id: 13, text: "A small, low-cost computer designed for individual use is a:", options: ["Mainframe", "Microcomputer", "Supercomputer", "Minicomputer"], correctAnswer: 1, category: "Categories" },
  { id: 14, text: "Minicomputers are also referred to as:", options: ["Microcomputers", "Midrange computers", "Mainframes", "PDAs"], correctAnswer: 1, category: "Categories" },
  { id: 15, text: "Which computer is used in large organizations (like banks) and accessed via terminals?", options: ["Microcomputer", "Mainframe computer", "Laptop", "Tablet"], correctAnswer: 1, category: "Categories" },
  { id: 16, text: "The speed of a Supercomputer is measured in:", options: ["MIPS", "MHz", "FLOPS", "Bytes"], correctAnswer: 2, category: "Categories" },
  { id: 17, text: "Handheld computers are also known as:", options: ["Mainframes", "Personal Digital Assistants (PDAs)", "Supercomputers", "Minicomputers"], correctAnswer: 1, category: "Categories" },
  // Part 4
  { id: 18, text: "The computer system consists of four parts: Hardware, Software, Data, and:", options: ["Internet", "Users", "Cables", "Electricity"], correctAnswer: 1, category: "System Basics" },
  { id: 19, text: "A set of instructions that tells the computer what to do is called a:", options: ["Data", "Program", "User", "Hardware"], correctAnswer: 1, category: "System Basics" },
  { id: 20, text: "Raw facts and figures processed by a computer are called:", options: ["Information", "Software", "Data", "Programs"], correctAnswer: 2, category: "System Basics" },
  { id: 21, text: "CPU stands for:", options: ["Central Process Unit", "Central Processing Unit", "Control Process Unit", "Core Processing Unit"], correctAnswer: 1, category: "Hardware" },
  { id: 22, text: "An integrated circuit that contains all the functions of a CPU is a:", options: ["Motherboard", "Microprocessor", "System Bus", "Controller"], correctAnswer: 1, category: "Hardware" },
  { id: 23, text: "The \"Brain\" of the computer is the:", options: ["RAM", "CPU", "Hard Disk", "Monitor"], correctAnswer: 1, category: "Hardware" },
  // Part 5
  { id: 24, text: "The different parts of the CPU are:", options: ["Input, Output, Storage", "CU, ALU, and Registers", "RAM, ROM, BIOS", "Data, Address, Control"], correctAnswer: 1, category: "Architecture" },
  { id: 25, text: "Which unit is responsible for performing mathematical and logical operations?", options: ["Control Unit (CU)", "Arithmetic Logic Unit (ALU)", "Memory Unit", "Input Unit"], correctAnswer: 1, category: "Architecture" },
  { id: 26, text: "The ALU consists of two units: Arithmetic unit and ________ unit:", options: ["Control", "Logic", "Storage", "Instruction"], correctAnswer: 1, category: "Architecture" },
  { id: 27, text: "The ________ unit performs comparisons like Equal to, Less than, or Greater than:", options: ["Arithmetic", "Logic", "Control", "Input"], correctAnswer: 1, category: "Architecture" },
  { id: 28, text: "Which part of the CPU is called the \"working memory\"?", options: ["RAM", "Registers", "ROM", "Cache"], correctAnswer: 1, category: "Architecture" },
  { id: 29, text: "The unit that directs and coordinates the flow of data is the:", options: ["ALU", "Control Unit (CU)", "Registers", "RAM"], correctAnswer: 1, category: "Architecture" },
  { id: 30, text: "\"Word size\" refers to:", options: ["Document size", "Number of bits a CPU can process at once", "Hard disk size", "Speed"], correctAnswer: 1, category: "Architecture" },
  { id: 31, text: "In a 64-bit processor, the register size is:", options: ["32 bits", "64 bits", "128 bits", "8 bits"], correctAnswer: 1, category: "Architecture" },
  // Part 6
  { id: 32, text: "Main memory consists of:", options: ["Hard Disk and SSD", "RAM and ROM", "Cache and Registers", "USB and CD"], correctAnswer: 1, category: "Memory" },
  { id: 33, text: "Which memory is used to store data and instructions DURING processing?", options: ["ROM", "RAM", "Hard Disk", "Flash Drive"], correctAnswer: 1, category: "Memory" },
  { id: 34, text: "BIOS (Standard processing programs) is stored in:", options: ["RAM", "ROM", "Cache", "Registers"], correctAnswer: 1, category: "Memory" },
  { id: 35, text: "RAM is called \"Volatile\" because:", options: ["It is very fast", "It loses its content when power is turned off", "it is permanent", "it is expensive"], correctAnswer: 1, category: "Memory" },
  { id: 36, text: "Cache memory is placed between:", options: ["RAM and Hard Disk", "CPU and RAM", "CPU and Keyboard", "Monitor and CPU"], correctAnswer: 1, category: "Memory" },
  { id: 37, text: "Cache memory is used to bridge the ________ gap between CPU and RAM:", options: ["Distance", "Price", "Speed", "Storage"], correctAnswer: 2, category: "Memory" },
  { id: 38, text: "There are usually ________ levels of cache memory:", options: ["1", "2", "3", "5"], correctAnswer: 2, category: "Memory" },
  { id: 39, text: "Secondary memory (e.g., Hard Disk) is:", options: ["Volatile", "Non-volatile (Permanent)", "Faster than RAM", "Directly accessed by CPU"], correctAnswer: 1, category: "Memory" },
  // Part 7
  { id: 40, text: "The \"Instruction Cycle\" follows which sequence?", options: ["Fetch -> Execute -> Decode -> Store", "Fetch -> Decode -> Execute -> Store", "Decode -> Fetch -> Store -> Execute", "Store -> Fetch -> Decode -> Execute"], correctAnswer: 1, category: "Cycle" },
  { id: 41, text: "Which step involves interpreting the instruction?", options: ["Fetch", "Decode", "Execute", "Store"], correctAnswer: 1, category: "Cycle" },
  { id: 42, text: "MIPS stands for:", options: ["Memory In Processing", "Millions of Instructions Per Second", "Main Input Power", "Micro Instruction Speed"], correctAnswer: 1, category: "Cycle" },
  { id: 43, text: "Which factor affects computer performance?", options: ["CPU speed", "RAM size", "Bus width", "All of the above"], correctAnswer: 3, category: "Performance" },
  { id: 44, text: "Microprocessors are classified as RISC or CISC based on their:", options: ["Size", "Instruction set", "Price", "Manufacture date"], correctAnswer: 1, category: "Performance" },
  // Part 8
  { id: 45, text: "The printed circuit board containing principal components is the:", options: ["Hard Drive", "Sound Card", "Motherboard", "Power Supply"], correctAnswer: 2, category: "Motherboard" },
  { id: 46, text: "\"Form Factor\" refers to the motherboard's:", options: ["Speed", "Price", "Geometry, dimensions, and layout", "Color"], correctAnswer: 2, category: "Motherboard" },
  { id: 47, text: "The most common motherboard design for desktops is:", options: ["micro-ATX", "ATX", "BTX", "ITX"], correctAnswer: 1, category: "Motherboard" },
  { id: 48, text: "The ________ is a set of chips that controls data flow between CPU and other devices:", options: ["BIOS", "Chipset", "CMOS", "Bus"], correctAnswer: 1, category: "Motherboard" },
  { id: 49, text: "Which chip stores configuration like date, time, and system settings?", options: ["BIOS", "CMOS", "RAM", "ALU"], correctAnswer: 1, category: "Motherboard" },
  { id: 50, text: "The System Clock is used to:", options: ["Show current time", "Synchronize and time all computer operations", "Cool the CPU", "Save files"], correctAnswer: 1, category: "Motherboard" },
  { id: 51, text: "Clock frequency is measured in:", options: ["Watts", "Volts", "Hertz (MHz/GHz)", "Amperes"], correctAnswer: 2, category: "Motherboard" },
  // Part 9
  { id: 52, text: "The process of starting the computer is called:", options: ["Formatting", "Saving", "Booting", "Deleting"], correctAnswer: 2, category: "Booting" },
  { id: 53, text: "POST stands for:", options: ["Power-On Self-Test", "Program Output System Test", "Primary Operating System Tool", "Post-Office Service Task"], correctAnswer: 0, category: "Booting" },
  { id: 54, text: "The function of BIOS is to:", options: ["Edit photos", "Perform the startup/booting process", "browse the web", "Calculate math"], correctAnswer: 1, category: "Booting" },
  // Part 10
  { id: 55, text: "A \"Bus\" is defined as:", options: ["A storage device", "A set of parallel wires for transmitting data", "A cooling system", "A software"], correctAnswer: 1, category: "Buses" },
  { id: 56, text: "The Internal Bus is also called the:", options: ["Expansion Bus", "External Bus", "System Bus", "USB Bus"], correctAnswer: 2, category: "Buses" },
  { id: 57, text: "The External Bus is also referred to as the:", options: ["System Bus", "Expansion Bus", "Address Bus", "Control Bus"], correctAnswer: 1, category: "Buses" },
  { id: 58, text: "Which bus carries the \"Command\" to access memory?", options: ["Data Bus", "Address Bus", "Control Bus", "System Bus"], correctAnswer: 2, category: "Buses" },
  { id: 59, text: "Which bus carries the \"Actual Data\"?", options: ["Address Bus", "Data Bus", "Control Bus", "External Bus"], correctAnswer: 1, category: "Buses" },
  { id: 60, text: "The width of which bus determines the maximum memory locations?", options: ["Data Bus", "Control Bus", "Address Bus", "System Bus"], correctAnswer: 2, category: "Buses" },
  { id: 61, text: "Computer speed is directly affected by the width of the:", options: ["Address Bus", "Data Bus", "Control Bus", "Power Bus"], correctAnswer: 1, category: "Buses" },
  // Part 11
  { id: 62, text: "Which port connects the monitor?", options: ["USB", "VGA", "RJ45", "Parallel"], correctAnswer: 1, category: "Ports" },
  { id: 63, text: "Which connector is used for Networking (Internet)?", options: ["PS/2", "RJ45", "VGA", "Serial"], correctAnswer: 1, category: "Ports" },
  { id: 64, text: "The Serial Port is typically used for:", options: ["Modern Printers", "External Modems/Old Mice", "Monitors", "Power"], correctAnswer: 1, category: "Ports" },
  { id: 65, text: "The Parallel Port was commonly used for:", options: ["Keyboard", "Older Printers", "Mouse", "Speakers"], correctAnswer: 1, category: "Ports" },
  { id: 66, text: "PS/2 Ports are used for attaching:", options: ["Internet cable", "Keyboard and Mouse", "Speakers", "Monitor"], correctAnswer: 1, category: "Ports" },
  { id: 67, text: "SCSI Port is used for:", options: ["Low speed devices", "High-speed disks/printers in a daisy chain", "Only monitors", "Webcams"], correctAnswer: 1, category: "Ports" },
  { id: 68, text: "USB stands for:", options: ["Unified Serial Bus", "Universal Serial Bus", "Unit Serial Base", "Ultra Speed Bus"], correctAnswer: 1, category: "Ports" },
  // Part 12
  { id: 69, text: "An expansion card is fixed on the motherboard in an:", options: ["Expansion Slot", "Input port", "CPU socket", "Power socket"], correctAnswer: 0, category: "Slots" },
  { id: 70, text: "Which slot is used for high-speed modern graphics cards?", options: ["ISA", "PCI", "PCI Express (PCIe)", "PC Card"], correctAnswer: 2, category: "Slots" },
  { id: 71, text: "Which slot is specifically for older, slower devices (Obsolete)?", options: ["ISA", "PCIe", "AGP", "PCI"], correctAnswer: 0, category: "Slots" },
  { id: 72, text: "PC Card slots are commonly found in:", options: ["Supercomputers", "Mainframes", "Laptops (Notebooks)", "Desktop towers"], correctAnswer: 2, category: "Slots" },
  // Part 13
  { id: 73, text: "The \"Stored Program Concept\" means:", options: ["Data is stored in books", "Both data and programs are stored in memory", "Programs are deleted after use", "Computers have no memory"], correctAnswer: 1, category: "Misc" },
  { id: 74, text: "The \"Instruction Set\" is:", options: ["A manual for users", "The set of basic operations a processor can perform", "A list of computer brands", "A type of keyboard"], correctAnswer: 1, category: "Misc" },
  { id: 75, text: "What describes the \"Input-Process-Output\" cycle?", options: ["How to buy a PC", "Fundamental working steps of a computer", "How to use a mouse", "Cleaning the hardware"], correctAnswer: 1, category: "Misc" },
  { id: 76, text: "Which of these is Hardware?", options: ["Windows 10", "MS Excel", "Hard Disk", "Google Chrome"], correctAnswer: 2, category: "Misc" },
  { id: 77, text: "1st Generation computers were:", options: ["Huge and took entire rooms", "Small like a phone", "Very fast", "Cheap"], correctAnswer: 0, category: "Generations" },
  { id: 78, text: "2nd Generation used ________ for storage:", options: ["Cloud", "Magnetic Tapes/Drums", "SSD", "Flash Memory"], correctAnswer: 1, category: "Generations" },
  { id: 79, text: "The unit of measure for CPU clock speed is:", options: ["GHz", "GB", "TB", "Watts"], correctAnswer: 0, category: "Architecture" },
  { id: 80, text: "Which component is the main circuit board of the computer?", options: ["Hard Disk", "Motherboard", "RAM", "PSU"], correctAnswer: 1, category: "Hardware" },
  { id: 81, text: "Which part of the CPU stores intermediate results?", options: ["ALU", "Registers", "CU", "RAM"], correctAnswer: 1, category: "Architecture" },
  { id: 82, text: "Floating point Operations Per Second (FLOPS) measures the speed of:", options: ["Laptops", "Supercomputers", "Printers", "Keyboards"], correctAnswer: 1, category: "Categories" },
  { id: 83, text: "A \"Terminal\" is used to access which type of computer?", options: ["PDA", "Mainframe", "Smartphone", "Calculator"], correctAnswer: 1, category: "Categories" },
  { id: 84, text: "Artificial Intelligence (AI) is the main focus of which generation?", options: ["3rd", "4th", "5th", "6th"], correctAnswer: 2, category: "Generations" },
  { id: 85, text: "\"Accuracy\" means the computer provides:", options: ["Slow results", "Errors frequently", "A high degree of correct results", "Random results"], correctAnswer: 2, category: "Characteristics" },
  { id: 86, text: "Which memory stores permanent instructions for the computer to start?", options: ["RAM", "ROM", "Cache", "Secondary"], correctAnswer: 1, category: "Memory" },
  { id: 87, text: "The width of the Data Bus is related to the ________ of the computer:", options: ["Weight", "Speed", "Color", "Height"], correctAnswer: 1, category: "Buses" },
];
